# Generated by Django 2.1.4 on 2019-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabnum', models.TextField()),
                ('fio', models.TextField()),
                ('gender', models.TextField()),
                ('birthdate', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Play',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
