# Generated by Django 2.1.4 on 2019-02-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190206_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_duration', models.IntegerField()),
                ('call_time', models.TimeField()),
                ('call_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AlterField(
            model_name='worker',
            name='tabnum',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='calls',
            name='call_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_from', to='blog.Worker'),
        ),
        migrations.AddField(
            model_name='calls',
            name='call_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_to', to='blog.Worker'),
        ),
    ]
