# Generated by Django 2.1.4 on 2019-02-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190206_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_theme', models.TextField()),
                ('letter_message', models.TextField()),
                ('letter_time', models.TimeField()),
                ('letter_date', models.DateField()),
                ('letter_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_from', to='blog.Worker')),
                ('letter_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_to', to='blog.Worker')),
            ],
        ),
    ]
