# Generated by Django 2.1.4 on 2019-02-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='letter_dict',
            field=models.TextField(null=True),
        ),
    ]
