# Generated by Django 2.1.4 on 2019-02-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_letter_letter_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('meet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meet_theme', models.TextField()),
                ('meet_subject', models.TextField()),
                ('meet_time', models.TimeField()),
                ('meet_date', models.DateField()),
                ('meet_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_participant', to='blog.Worker')),
            ],
        ),
    ]
