# Generated by Django 2.1.4 on 2019-02-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meet',
            name='meet_id',
            field=models.IntegerField(),
        ),
    ]
