# Generated by Django 2.1.4 on 2019-02-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190221_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='meet_id',
        ),
    ]
