# Generated by Django 2.1.4 on 2019-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_meet_meet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='meet_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
