# Generated by Django 2.1.4 on 2019-02-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_meet_meet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='meet_participant',
        ),
        migrations.DeleteModel(
            name='Meet',
        ),
    ]
