# Generated by Django 2.1.4 on 2019-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190221_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='meet_id',
        ),
        migrations.AlterField(
            model_name='meet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
