# Generated by Django 2.1.4 on 2019-02-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_meet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synt_id', models.CharField(max_length=50)),
                ('stat_letters', models.IntegerField()),
                ('stat_calls', models.IntegerField()),
                ('stat_meets', models.IntegerField()),
                ('stat_result', models.IntegerField()),
                ('first_tabnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_tabnum', to='blog.Worker')),
                ('second_tabnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_tabnum', to='blog.Worker')),
            ],
        ),
    ]
